# Generated by Django 5.0.13 on 2025-05-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DF', 'Borrador'), ('PB', 'Publicado'), ('UR', 'En revisión'), ('AR', 'Archivado')], default='DF', max_length=2, verbose_name='article status'),
        ),
    ]
