# Generated by Django 5.0.13 on 2025-05-12 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf',
            field=models.FileField(null=True, upload_to='articles/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='archivo PDF'),
        ),
    ]
