# Generated by Django 5.0.13 on 2025-05-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_abstract_alter_article_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='fecha de creación'),
        ),
    ]
