# Generated by Django 5.0.13 on 2025-07-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, default='', help_text='Digital Object Identifier for the article', max_length=100, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='article',
            name='issn',
            field=models.CharField(blank=True, default='', help_text='International Standard Serial Number for the article', max_length=100, verbose_name='ISSN'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='name',
            field=models.CharField(help_text='Unique name for the article tag', max_length=50, unique=True, verbose_name='article tag name'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(help_text='Unique slug for the article tag', unique=True, verbose_name='article tag slug'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['doi'], name='articles_ar_doi_f0d052_idx'),
        ),
    ]
