# Generated by Django 5.0.13 on 2025-07-25 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_authors_alter_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publication_date'], 'verbose_name': 'article:verbose_name', 'verbose_name_plural': 'article:verbose_name_plural'},
        ),
        migrations.RemoveIndex(
            model_name='articletag',
            name='articles_ar_name_6b7ff8_idx',
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='name',
        ),
        migrations.AddField(
            model_name='articletag',
            name='tag',
            field=models.CharField(default='', help_text='publication:model_tag_help_text', max_length=255, unique=True, verbose_name='publication:model_tag_verbose_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(blank=True, default='', help_text='publication:model_authors_help_text', max_length=255, verbose_name='publication:model_authors_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, help_text='publication:model_body_help_text', verbose_name='publication:model_body_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='publication:model_created_at_help_text', verbose_name='publication:model_created_at_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, default='', help_text='article:model_doi_help_text', max_length=100, verbose_name='article:model_doi_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='issn',
            field=models.CharField(blank=True, default='', help_text='article:model_issn_help_text', max_length=100, verbose_name='article:model_issn_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf',
            field=models.FileField(help_text='article:model_pdf_help_text', null=True, upload_to='articles/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='article:model_pdf_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(blank=True, help_text='publication:model_publication_date_help_text', null=True, verbose_name='publication:model_publication_date_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='publication:model_slug_help_text', max_length=200, unique=True, verbose_name='publication:model_slug_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DF', 'publication:status_draft'), ('PB', 'publication:status_published'), ('UR', 'publication:status_under_review'), ('AR', 'publication:status_archived')], default='DF', help_text='publication:model_status_help_text', max_length=2, verbose_name='publication:model_status_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(help_text='article:model_tags_help_text', related_name='articles', to='articles.articletag', verbose_name='article:model_tags_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='publication:model_title_help_text', max_length=255, unique=True, verbose_name='publication:model_title_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='publication:model_updated_at_help_text', verbose_name='publication:model_updated_at_verbose_name'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='slug',
            field=models.SlugField(help_text='publication:model_slug_help_text', max_length=200, unique=True, verbose_name='publication:model_slug_verbose_name'),
        ),
        migrations.AddIndex(
            model_name='articletag',
            index=models.Index(fields=['tag'], name='articles_ar_tag_848f49_idx'),
        ),
    ]
