# Generated by Django 5.0.13 on 2025-07-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='publication:model_summary_help_text', max_length=500, verbose_name='publication:model_summary_verbose_name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, help_text='article:model_abstract_help_text abstract', verbose_name='article:model_abstract_verbose_name'),
        ),
    ]
