# Generated by Django 5.0.13 on 2025-07-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_summary_alter_article_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='abstract',
        ),
    ]
