# Generated by Django 5.1.5 on 2025-01-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
