services:
  docs:
    image: the_green_economics_local_docs
    container_name: the_green_economics_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./the_green_economics:/app/the_green_economics:z
    ports:
      - '9000:9000'
    command: /start-docs
