# Generated by Django 5.0.13 on 2025-04-09 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='news tag name')),
                ('slug', models.SlugField(unique=True, verbose_name='news tag slug')),
            ],
            options={
                'verbose_name': 'news tag',
                'verbose_name_plural': 'news tags',
                'indexes': [models.Index(fields=['name'], name='news_newsta_name_f56252_idx'), models.Index(fields=['slug'], name='news_newsta_slug_6443f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='news title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='news slug')),
                ('body', models.TextField(verbose_name='news content')),
                ('excerpt', models.CharField(blank=True, max_length=200, verbose_name='news excerpt')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='new featured image')),
                ('publication_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='new publication date')),
                ('status', models.CharField(choices=[('DF', 'Borrador'), ('PB', 'Publicado'), ('AR', 'Archivado')], db_index=True, default='DF', max_length=2, verbose_name='news status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='news creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='news update date')),
                ('tags', models.ManyToManyField(blank=True, related_name='news', to='news.newstag', verbose_name='news tags')),
            ],
            options={
                'verbose_name': 'news item',
                'verbose_name_plural': 'news',
                'ordering': ['-publication_date'],
                'indexes': [models.Index(fields=['publication_date', 'status'], name='news_news_publica_4ccdb2_idx'), models.Index(fields=['slug', 'status'], name='news_news_slug_5e74e9_idx')],
            },
        ),
    ]
