# Generated by Django 5.0.13 on 2025-07-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publication_date'], 'verbose_name': 'news:model_verbose_name', 'verbose_name_plural': 'news:model_verbose_name_plural'},
        ),
        migrations.AlterModelOptions(
            name='newstag',
            options={'verbose_name': 'news_tag:model_verbose_name', 'verbose_name_plural': 'news_tag:model_verbose_name_plural'},
        ),
        migrations.RemoveIndex(
            model_name='newstag',
            name='news_newsta_name_f56252_idx',
        ),
        migrations.RemoveField(
            model_name='newstag',
            name='name',
        ),
        migrations.AddField(
            model_name='news',
            name='authors',
            field=models.CharField(blank=True, default='', help_text='publication:model_authors_help_text', max_length=255, verbose_name='publication:model_authors_verbose_name'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='tag',
            field=models.CharField(default='', help_text='publication:model_tag_help_text', max_length=255, unique=True, verbose_name='publication:model_tag_verbose_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, help_text='publication:model_body_help_text', verbose_name='publication:model_body_verbose_name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='publication:model_created_at_help_text', verbose_name='publication:model_created_at_verbose_name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.CharField(blank=True, help_text='news:model_excerpt_help_text', max_length=200, verbose_name='news:model_excerpt_verbose_name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(help_text='news:model_featured_image_help_text', null=True, upload_to='news/images/', verbose_name='news:model_featured_image_verbose_name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateField(blank=True, help_text='publication:model_publication_date_help_text', null=True, verbose_name='publication:model_publication_date_verbose_name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(help_text='publication:model_slug_help_text', max_length=200, unique=True, verbose_name='publication:model_slug_verbose_name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('DF', 'publication:status_draft'), ('PB', 'publication:status_published'), ('UR', 'publication:status_under_review'), ('AR', 'publication:status_archived')], default='DF', help_text='publication:model_status_help_text', max_length=2, verbose_name='publication:model_status_verbose_name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='news:model_tags_help_text', related_name='news', to='news.newstag', verbose_name='news:model_tags_verbose_name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='publication:model_title_help_text', max_length=255, unique=True, verbose_name='publication:model_title_verbose_name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='publication:model_updated_at_help_text', verbose_name='publication:model_updated_at_verbose_name'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='slug',
            field=models.SlugField(help_text='publication:model_slug_help_text', max_length=200, unique=True, verbose_name='publication:model_slug_verbose_name'),
        ),
        migrations.AddIndex(
            model_name='newstag',
            index=models.Index(fields=['tag'], name='news_newsta_tag_8a7c1c_idx'),
        ),
    ]
