# Generated by Django 5.0.13 on 2025-07-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_newstag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='publication:model_summary_help_text', max_length=500, verbose_name='publication:model_summary_verbose_name'),
        ),
    ]
