# Generated by Django 5.0.13 on 2025-07-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='research_proposal:first_name_help_text', max_length=100, verbose_name='research_proposal:first_name_verbose_name')),
                ('last_name', models.CharField(help_text='research_proposal:last_name_help_text', max_length=100, verbose_name='research_proposal:last_name_verbose_name')),
                ('email', models.EmailField(help_text='research_proposal:email_help_text', max_length=254, verbose_name='research_proposal:email_verbose_name')),
                ('phone', models.CharField(help_text='research_proposal:phone_help_text', max_length=20, verbose_name='research_proposal:phone_verbose_name')),
                ('institution', models.CharField(help_text='research_proposal:institution_help_text', max_length=200, verbose_name='research_proposal:institution_verbose_name')),
                ('title', models.CharField(help_text='research_proposal:title_help_text', max_length=255, verbose_name='research_proposal:title_verbose_name')),
                ('research_area', models.CharField(choices=[('bs', 'research_proposal:basic_research'), ('ad', 'research_proposal:advanced_research'), ('ar', 'research_proposal:applied_research'), ('dr', 'research_proposal:developmental_research'), ('cs', 'research_proposal:case_study'), ('lr', 'research_proposal:literature_review'), ('ma', 'research_proposal:meta_analysis'), ('sr', 'research_proposal:systematic_review'), ('fs', 'research_proposal:field_study'), ('er', 'research_proposal:experimental_research'), ('sre', 'research_proposal:survey_research'), ('ot', 'research_proposal:other')], help_text='research_proposal:research_area_help_text', max_length=50, verbose_name='research_proposal:research_area_verbose_name')),
                ('abstract', models.TextField(help_text='research_proposal:abstract_help_text', verbose_name='research_proposal:abstract_verbose_name')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='research_proposal:creation_date_help_text', verbose_name='research_proposal:creation_date_verbose_name')),
            ],
            options={
                'verbose_name': 'research_proposal:verbose_name',
                'verbose_name_plural': 'research_proposal:verbose_name_plural',
                'ordering': ['-creation_date'],
                'indexes': [models.Index(fields=['email', 'creation_date'], name='contacts_re_email_0516d3_idx')],
                'unique_together': {('email', 'creation_date'), ('first_name', 'last_name', 'institution')},
            },
        ),
    ]
