# Generated by Django 5.0.13 on 2025-07-27 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchproposal',
            options={'get_latest_by': 'creation_date', 'ordering': ['-creation_date'], 'verbose_name': 'research_proposal:verbose_name', 'verbose_name_plural': 'research_proposal:verbose_name_plural'},
        ),
    ]
