# Generated by Django 5.0.13 on 2025-08-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_researchproposal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproposal',
            name='research_area',
            field=models.CharField(choices=[('bs', 'Economía Circular'), ('er', 'Energía Renovable'), ('ds', 'Desarrollo Sostenible'), ('pa', 'Política Ambiental'), ('fv', 'Finanzas Verdes'), ('ot', 'Otros')], help_text='research_proposal:research_area_help_text', max_length=50, verbose_name='research_proposal:research_area_verbose_name'),
        ),
    ]
