# Generated by Django 5.0.13 on 2025-07-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='user:model_name_help_text', max_length=255, verbose_name='user:model_name_verbose_name'),
        ),
    ]
